### ISSUE TITLE
Intel compiler compatibility issues

### ISSUE THREAD

**Issue by mohamso** [tud-zih-energy/phdeem#2]
Hello:

I do not think phdeem plays well with the intel compiler on Taurus.
I tested with the intel/2016.2.181 module and I got the following error "error: incomplete type is not allowed". Please see the attached error file.

When I compile the project using the gcc/5.3.0 module, everything works according to the README.md file.

[phdeem_error.txt](https://github.com/tud-zih-energy/phdeem/files/517859/phdeem_error.txt)

**Comment by Ferruck** [comment]
I can retrace your problem.

You could simply load the `intel/2017.0.020` module, with this version the plugin builds fine for me. If this is a solution for you, please let me know, otherwise as well.

Nevertheless I'll have to investigate this further.

**Comment by tilsche** [comment]
This is a nasty stupid issue with feature flags and the availability of the struct timepec. The official way is to include _hdeem.h_ (and thus _phdeem.h_ transitively) **first** and let it do some feature flag magic. It can't do that if time.h is included already. Alternatively you can use c11 / gnu11, or just remove -ansi, well, or just play around with -std/_XOPEN_SOURCE/_POSIX_SOURCE/_DEFAULT_SOURCE until it works.

Note that -ansi and -std=gnu99 at the same time doesn't make any sense:

```
       -ansi
           In C mode, this is equivalent to -std=c90. 
```

**Comment by Ferruck** [comment]
Of course defining both `-ansi` and `-std=gnu99` at the same time doesn't make any sense. Sorry for that, I removed it.
